/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { X2Y2R1 } from "./X2Y2R1";
export * as factories from "./factories";
export { X2Y2R1__factory } from "./factories/X2Y2R1__factory";
